var Descriptions= {
    "momo" : "Horizontal moment rounded"
    ,"momv" : "Vertical moment rounded"
    ,momX : "Horizontal moment rounded"
    ,momY : "Vertical moment rounded"    
    ,momentrel : "Relative moment"
    ,m1o: "Horizontal moment"
    ,m1v: "Vertical moment"
    ,m1X: "Horizontal moment"
    ,m1Y: "Vertical moment"  
    ,m1otot: "Total horizontal moment"
    ,m1vtot: "Total verical moment"
    ,m1Xtot: "Total horizontal moment"
    ,m1Ytot: "Total verical moment"    
    ,M1: "Distance between total moments"
    ,moment: "Average moment"
    ,mHydr:"Sum of hydrophobicity"
    ,hydr:"Hydrophobicity value"
};
